// Red Team Buyer Evaluation Report Template
//
// This is a template. The /run-evaluation command will create a copy
// with all {{PLACEHOLDER}} values filled in before compiling.

#set document(
  title: "Red Team Buyer Evaluation",
  author: "Claude Red Team Buyer Agent",
)

#set page(
  paper: "a4",
  margin: (top: 2.5cm, bottom: 2.5cm, left: 2cm, right: 2cm),
  header: align(right)[
    #text(size: 8pt, fill: gray)[Red Team Buyer Evaluation]
  ],
  footer: align(center)[
    #text(size: 8pt, fill: gray)[Page #counter(page).display() of #locate(loc => {counter(page).final(loc).first()})]
  ],
)

#set text(font: "New Computer Modern", size: 10pt)
#set heading(numbering: "1.1")
#set par(justify: true)

// Title Page
#align(center)[
  #v(3cm)
  #text(size: 28pt, weight: "bold")[Red Team Buyer\ Evaluation Report]
  #v(1cm)
  #text(size: 14pt, fill: gray)[Website Analysis from a Buyer's Perspective]
  #v(2cm)
  #line(length: 60%, stroke: 0.5pt + gray)
  #v(0.5cm)
  #text(size: 12pt)[*Target:* {{TARGET_URL}}]
  #v(0.3cm)
  #text(size: 12pt)[*Date:* {{EVALUATION_DATE}}]
  #v(0.3cm)
  #text(size: 12pt)[*Method:* {{BROWSING_METHOD}}]
  #v(3cm)
  #text(size: 11pt, fill: gray)[Generated by Claude Red Team Buyer Agent]
]

#pagebreak()

// Table of Contents
#outline(indent: 1.5em, depth: 2)

#pagebreak()

= Executive Summary

{{EXECUTIVE_SUMMARY}}

#v(0.5cm)

#align(center)[
  #rect(
    width: 60%,
    fill: luma(245),
    inset: 1em,
    radius: 4pt,
  )[
    #align(center)[
      #text(size: 12pt)[*Overall Score*]
      #v(0.3cm)
      #text(size: 36pt, weight: "bold")[{{OVERALL_SCORE}} / 10]
    ]
  ]
]

#v(0.5cm)

== Evaluation Context

*Objective:* {{OBJECTIVE}}

*Pages Visited:* {{PAGES_VISITED}}

#pagebreak()

= Score Overview

#table(
  columns: (1fr, auto, 3fr),
  inset: 8pt,
  align: (left, center, left),
  stroke: 0.5pt + gray,
  [*Dimension*], [*Score*], [*Summary*],
  {{SCORE_TABLE_ROWS}}
)

#pagebreak()

= Detailed Findings

{{DETAILED_SECTIONS}}

#pagebreak()

= Top Recommended Improvements

These are the highest-impact changes, prioritized by potential effect on buyer conversion:

{{TOP_IMPROVEMENTS}}

#pagebreak()

= Buyer Verdict

{{BUYER_VERDICT}}

#v(2cm)
#line(length: 100%, stroke: 0.5pt + gray)
#v(0.5cm)
#text(size: 8pt, fill: gray)[
  This report was generated automatically by the Claude Red Team Buyer agent.
  It represents a simulated buyer evaluation and should be used as one input among many
  when making website improvement decisions.
]
